"""Render a benchmark results.json as markdown tables + log-log slopes.

Post-processing only: reads a results file produced by one of the
scripts in ../benchmarks/ and prints (a) one markdown table per method
group and (b) the least-squares slope of log(median total) vs log(x),
where x is the numeric parameter in each benchmark name (``n=...`` or
``depth=...``). Slope ~1 means linear total cost, ~2 quadratic.

Usage:

    uv run python papers/incremental-bpe-tokenization/scripts/analyze_run.py \
        papers/incremental-bpe-tokenization/benchmarks/runs/<run>/results.json
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path
from typing import Any


def group_benchmarks(payload: dict[str, Any]) -> dict[str, list[tuple[int, dict[str, Any]]]]:
    groups: dict[str, list[tuple[int, dict[str, Any]]]] = {}
    for bench in payload["benchmarks"]:
        method, _, param = bench["name"].partition("/")
        x = int(param.split("=")[1])
        groups.setdefault(method, []).append((x, bench))
    for rows in groups.values():
        rows.sort(key=lambda row: row[0])
    return groups


def loglog_slope(rows: list[tuple[int, dict[str, Any]]]) -> float:
    xs = [math.log(x) for x, _ in rows]
    ys = [math.log(b["median_ns"]) for _, b in rows]
    mx = sum(xs) / len(xs)
    my = sum(ys) / len(ys)
    return sum((x - mx) * (y - my) for x, y in zip(xs, ys, strict=True)) / sum(
        (x - mx) ** 2 for x in xs
    )


def render(payload: dict[str, Any]) -> str:
    lines: list[str] = []
    for method, rows in group_benchmarks(payload).items():
        param_name = rows[0][1]["name"].partition("/")[2].split("=")[0]
        lines.append(f"### `{method}`")
        lines.append("")
        lines.append(f"| {param_name} | median | mean | stdev | CV |")
        lines.append("|---|---|---|---|---|")
        for x, b in rows:
            cv = b["stdev_ns"] / b["mean_ns"] * 100 if b["mean_ns"] else 0.0
            lines.append(
                f"| {x} | {b['median_ns'] / 1e6:.3f} ms | {b['mean_ns'] / 1e6:.3f} ms "
                f"| {b['stdev_ns'] / 1e6:.3f} ms | {cv:.1f}% |"
            )
        lines.append("")
        if len(rows) >= 3:
            lines.append(
                f"log-log slope of median vs {param_name}: **{loglog_slope(rows):.3f}** "
                "(1.0 = linear, 2.0 = quadratic)"
            )
            lines.append("")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    payload = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    print(f"<!-- generated by scripts/analyze_run.py from {sys.argv[1]} -->")
    print()
    print(render(payload))


if __name__ == "__main__":
    main()
